### ISSUE TITLE
Bad projection of point cloud

### ISSUE THREAD

**Issue by gottesman** [inuex35/ind-bermuda-opensfm#1]
I just finished processing the data through this process to get the point clouds from 360° images. I'm doing tests for a very large project of a whole city. The first test I did (less than 100 images) went out well, but now that I tried using o bit more (almost 5 thousand images), it didnt turn out good. The point cloud is distorted in a kind of a sphere, and some cameras ar not aligned, creating weird structures within the point cloud.

![1](https://github.com/inuex35/ind-bermuda-opensfm/assets/8980291/2d1f88ff-95ea-4c32-9376-6e0c428836fb)
![2](https://github.com/inuex35/ind-bermuda-opensfm/assets/8980291/50764818-3f66-4a7b-81fa-13ff1303ac6f)
![3](https://github.com/inuex35/ind-bermuda-opensfm/assets/8980291/a2802d80-30a4-4f19-874b-7bd3656d7faa)

Here in the "street view" mode in the viewer I can see a bit of distortion in the image that was "undistorted" in the process.
![4](https://github.com/inuex35/ind-bermuda-opensfm/assets/8980291/ee322189-c6af-49d1-976e-c07de12081e0)

Here is one of the images precisely in the same area as the picture above.
![5](https://github.com/inuex35/ind-bermuda-opensfm/assets/8980291/73ce24e2-c6b8-43f8-9ea8-581f24643a00)

I have done everyhting just as described in the README, the images have GPS metadata, they just lack the capture time.
![6](https://github.com/inuex35/ind-bermuda-opensfm/assets/8980291/961723ba-620d-4d17-ad0c-39a3a2de8af2)

Is there anything you can help me with? Maybe it's just something I'm doing wrong. Or the processed was never ment for very large projects.

Thank you in advance, and I'm sorry I'm not that good with english.

**Comment by inuex35** [comment]
Hello, sorry for the late reply.
Do you use altitude from the EXIF tag?
Because when you use EXIF GPS data, you might be accumulating errors as you only use nearby images.
